//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificado
    {
        public Nullable<decimal> nota_final { get; set; }
        public Nullable<System.DateTime> data_conclusao { get; set; }
        public decimal aluno { get; set; }
    
        public virtual Aluno Aluno1 { get; set; }
    }
}
